// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoolManager.Core.Persistence;

#nullable disable

namespace ScoolManager.Core.Persistence.Migrations
{
    [DbContext(typeof(ScoolManagerDbContext))]
    [Migration("20260809012124_AlunoSaudeNaturalidadeETipoCobranca")]
    partial class AlunoSaudeNaturalidadeETipoCobranca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ScoolManager.Core.Entities.Alunos.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnoLectivoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataMatricula")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoCondicaoMedica")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotografiaCaminho")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naturalidade")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroBiCedula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TemCondicaoMedica")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurmaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnoLectivoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Alunos.DocumentoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataUpload")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivo")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("DocumentosAluno", (string)null);
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Alunos.Encarregado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Profissao")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Encarregados", (string)null);
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Configuracoes.BackupRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhNaNuvem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Backups", (string)null);
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Configuracoes.ConfiguracaoBackup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BackupDiarioAutomatico")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotificarFalhasEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SincronizacaoNuvem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimaVerificacaoIntegridade")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesBackup", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackupDiarioAutomatico = false,
                            NotificarFalhasEmail = false,
                            SincronizacaoNuvem = false
                        });
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Configuracoes.DadosInstituicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAdministrativo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoCompleto")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogotipoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeInstituicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonePrincipal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneSecundario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DadosInstituicao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAdministrativo = "",
                            EnderecoCompleto = "",
                            Nif = "",
                            NomeInstituicao = "",
                            TelefonePrincipal = ""
                        });
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Escola.AnoLectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnosLectivos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataInicio = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataTermino = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "Aberto",
                            Nome = "2025/2026"
                        });
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Escola.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nivel = "Primario",
                            Numero = 1
                        },
                        new
                        {
                            Id = 2,
                            Nivel = "Primario",
                            Numero = 2
                        },
                        new
                        {
                            Id = 3,
                            Nivel = "Primario",
                            Numero = 3
                        },
                        new
                        {
                            Id = 4,
                            Nivel = "Primario",
                            Numero = 4
                        },
                        new
                        {
                            Id = 5,
                            Nivel = "Primario",
                            Numero = 5
                        },
                        new
                        {
                            Id = 6,
                            Nivel = "Primario",
                            Numero = 6
                        },
                        new
                        {
                            Id = 7,
                            Nivel = "Secundario",
                            Numero = 7
                        },
                        new
                        {
                            Id = 8,
                            Nivel = "Secundario",
                            Numero = 8
                        },
                        new
                        {
                            Id = 9,
                            Nivel = "Secundario",
                            Numero = 9
                        },
                        new
                        {
                            Id = 10,
                            Nivel = "Medio",
                            Numero = 10
                        },
                        new
                        {
                            Id = 11,
                            Nivel = "Medio",
                            Numero = 11
                        },
                        new
                        {
                            Id = 12,
                            Nivel = "Medio",
                            Numero = 12
                        },
                        new
                        {
                            Id = 13,
                            Nivel = "Medio",
                            Numero = 13
                        });
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Escola.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cursos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Gestão de Redes e Sistemas Informáticos",
                            Sigla = "GRSI"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Gestão de Recursos Humanos",
                            Sigla = "GRH"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Gestão Empresarial",
                            Sigla = "GE"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Ciências Físicas e Biológicas",
                            Sigla = "CFB"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Ciências Jurídicas",
                            Sigla = "CJ"
                        });
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Escola.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bloco")
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Salas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bloco = "Bloco A",
                            Capacidade = 40,
                            Nome = "Sala 01"
                        },
                        new
                        {
                            Id = 2,
                            Bloco = "Bloco A",
                            Capacidade = 40,
                            Nome = "Sala 04"
                        },
                        new
                        {
                            Id = 3,
                            Bloco = "Bloco B",
                            Capacidade = 40,
                            Nome = "Sala 08"
                        },
                        new
                        {
                            Id = 4,
                            Bloco = "Bloco B",
                            Capacidade = 40,
                            Nome = "Sala 12"
                        },
                        new
                        {
                            Id = 5,
                            Bloco = "Bloco C",
                            Capacidade = 25,
                            Nome = "Lab Info 2",
                            Observacoes = "Computadores - requer marcação prévia"
                        },
                        new
                        {
                            Id = 6,
                            Bloco = "Bloco C",
                            Capacidade = 30,
                            Nome = "Oficina B"
                        });
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Escola.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoLectivoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClasseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<char>("Letra")
                        .HasColumnType("TEXT");

                    b.Property<int>("Matriculados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnoLectivoId");

                    b.HasIndex("ClasseId");

                    b.HasIndex("CursoId");

                    b.HasIndex("SalaId");

                    b.ToTable("Turmas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoLectivoId = 1,
                            Capacidade = 40,
                            ClasseId = 7,
                            Letra = 'A',
                            Matriculados = 24,
                            SalaId = 1,
                            Turno = "Manha"
                        },
                        new
                        {
                            Id = 2,
                            AnoLectivoId = 1,
                            Capacidade = 40,
                            ClasseId = 7,
                            Letra = 'B',
                            Matriculados = 36,
                            SalaId = 1,
                            Turno = "Tarde"
                        },
                        new
                        {
                            Id = 3,
                            AnoLectivoId = 1,
                            Capacidade = 25,
                            ClasseId = 10,
                            CursoId = 1,
                            Letra = 'A',
                            Matriculados = 25,
                            SalaId = 5,
                            Turno = "Noite"
                        },
                        new
                        {
                            Id = 4,
                            AnoLectivoId = 1,
                            Capacidade = 40,
                            ClasseId = 10,
                            CursoId = 1,
                            Letra = 'B',
                            Matriculados = 28,
                            SalaId = 4,
                            Turno = "Tarde"
                        },
                        new
                        {
                            Id = 5,
                            AnoLectivoId = 1,
                            Capacidade = 40,
                            ClasseId = 10,
                            CursoId = 4,
                            Letra = 'A',
                            Matriculados = 32,
                            SalaId = 2,
                            Turno = "Manha"
                        },
                        new
                        {
                            Id = 6,
                            AnoLectivoId = 1,
                            Capacidade = 40,
                            ClasseId = 11,
                            CursoId = 4,
                            Letra = 'A',
                            Matriculados = 28,
                            SalaId = 4,
                            Turno = "Tarde"
                        },
                        new
                        {
                            Id = 7,
                            AnoLectivoId = 1,
                            Capacidade = 40,
                            ClasseId = 12,
                            CursoId = 3,
                            Letra = 'A',
                            Matriculados = 40,
                            SalaId = 3,
                            Turno = "Manha"
                        });
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Financeiro.MovimentoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessaoCaixaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SessaoCaixaId");

                    b.ToTable("MovimentosCaixa", (string)null);
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Financeiro.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anulado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoPagamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoAnulacao")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroRecibo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessaoCaixaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("SessaoCaixaId");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Financeiro.SessaoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SaldoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UtilizadorAberturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UtilizadorFechamentoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorAberturaId");

                    b.HasIndex("UtilizadorFechamentoId");

                    b.ToTable("SessoesCaixa", (string)null);
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Identidade.PerfilPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Configuracoes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EditarAlunos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Financeiro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Relatorios")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VerAlunos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PerfisPermissao", (string)null);
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Identidade.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PerfilPermissaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PerfilPermissaoId");

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("Utilizadores", (string)null);
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Notificacoes.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Lida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notificacoes", (string)null);
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Alunos.Aluno", b =>
                {
                    b.HasOne("ScoolManager.Core.Entities.Escola.AnoLectivo", "AnoLectivo")
                        .WithMany()
                        .HasForeignKey("AnoLectivoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScoolManager.Core.Entities.Escola.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnoLectivo");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Alunos.DocumentoAluno", b =>
                {
                    b.HasOne("ScoolManager.Core.Entities.Alunos.Aluno", "Aluno")
                        .WithMany("Documentos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Alunos.Encarregado", b =>
                {
                    b.HasOne("ScoolManager.Core.Entities.Alunos.Aluno", "Aluno")
                        .WithMany("Encarregados")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Escola.Turma", b =>
                {
                    b.HasOne("ScoolManager.Core.Entities.Escola.AnoLectivo", "AnoLectivo")
                        .WithMany()
                        .HasForeignKey("AnoLectivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoolManager.Core.Entities.Escola.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoolManager.Core.Entities.Escola.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScoolManager.Core.Entities.Escola.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnoLectivo");

                    b.Navigation("Classe");

                    b.Navigation("Curso");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Financeiro.MovimentoCaixa", b =>
                {
                    b.HasOne("ScoolManager.Core.Entities.Financeiro.SessaoCaixa", "SessaoCaixa")
                        .WithMany("Movimentos")
                        .HasForeignKey("SessaoCaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SessaoCaixa");
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Financeiro.Pagamento", b =>
                {
                    b.HasOne("ScoolManager.Core.Entities.Alunos.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoolManager.Core.Entities.Financeiro.SessaoCaixa", "SessaoCaixa")
                        .WithMany("Pagamentos")
                        .HasForeignKey("SessaoCaixaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aluno");

                    b.Navigation("SessaoCaixa");
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Financeiro.SessaoCaixa", b =>
                {
                    b.HasOne("ScoolManager.Core.Entities.Identidade.Utilizador", "UtilizadorAbertura")
                        .WithMany()
                        .HasForeignKey("UtilizadorAberturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoolManager.Core.Entities.Identidade.Utilizador", "UtilizadorFechamento")
                        .WithMany()
                        .HasForeignKey("UtilizadorFechamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UtilizadorAbertura");

                    b.Navigation("UtilizadorFechamento");
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Identidade.Utilizador", b =>
                {
                    b.HasOne("ScoolManager.Core.Entities.Identidade.PerfilPermissao", "PerfilPermissao")
                        .WithMany()
                        .HasForeignKey("PerfilPermissaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PerfilPermissao");
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Alunos.Aluno", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Encarregados");
                });

            modelBuilder.Entity("ScoolManager.Core.Entities.Financeiro.SessaoCaixa", b =>
                {
                    b.Navigation("Movimentos");

                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
